# Generated by Django 4.2.16 on 2024-09-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastercard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
