# Generated by Django 4.2.16 on 2024-09-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastercard_app', '0002_popularcards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularcards',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
