# Generated by Django 4.2.16 on 2024-09-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mastercard_app', '0005_title_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='FilterCategory',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='SubCategories',
        ),
    ]
