# Generated by Django 4.2.16 on 2024-10-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mastercard_app', '0006_rename_title_filtercategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=255)),
                ('cardImageUrl', models.ImageField(upload_to='offering_cards/')),
                ('applyNowUrl', models.URLField()),
                ('rateFeesUrl', models.URLField()),
                ('cardheadLine', models.CharField(max_length=255)),
                ('cardDescription', models.TextField()),
                ('annualFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specialFees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoryList', models.ManyToManyField(related_name='offering_cards', to='mastercard_app.subcategories')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastercard_app.subcategories')),
            ],
        ),
    ]
